# Generated by Django 5.0.1 on 2026-01-09 14:42

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('full_name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(db_index=True, max_length=20, unique=True)),
                ('organization', models.CharField(max_length=255)),
                ('subscription_status', models.CharField(choices=[('NONE', 'None'), ('PENDING', 'Pending'), ('ACTIVE', 'Active')], default='NONE', max_length=10)),
                ('subscription_expiry', models.DateTimeField(blank=True, null=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('history', models.JSONField(blank=True, default=list)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='SavedDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('doc_type', models.CharField(choices=[('HISOBOT', 'Hisobot (Tahliliy)'), ('AHBOROTNOMA', 'Axborotnoma (Newsletter)'), ('MAORUZA', "Ma'ruza (Rasmiy)"), ('NUTQ', 'Nutq (Tantanali/Ilhomlantiruvchi)'), ('TABRIK', 'Tabrik Matni'), ('BUYRUQ', 'Buyruq / Qaror loyihasi'), ('ARIZA', 'Ariza / Tushuntirish xati'), ('STRATEGIYA', 'Rivojlanish Strategiyasi'), ('MATBUOT', 'Matbuot xabari (Press Release)')], max_length=20)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'saved_documents',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['phone_number'], name='users_phone_n_a3b1c5_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['subscription_status'], name='users_subscri_ae2c5f_idx'),
        ),
        migrations.AddIndex(
            model_name='saveddocument',
            index=models.Index(fields=['user', '-created_at'], name='saved_docum_user_id_abce2a_idx'),
        ),
    ]
