# Generated by Django 5.0.1 on 2026-01-21 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_systemsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='receipt_file_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
